### ISSUE TITLE
404 - Broken page 

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/static-budget-portal#284]
https://vulekamali.gov.za/search-result?search_type=full-search&search=Post%20school%20education%20and%20training

**Comment by jbothma** [comment]
How do you end up here?

**Comment by adieyal** [comment]
<img width="886" alt="screen shot 2018-04-10 at 11 43 22" src="https://user-images.githubusercontent.com/420786/38549489-67799a7c-3cb4-11e8-8125-0aa9ed342aef.png">

**Comment by jbothma** [comment]
Thanks, added to pivotal https://www.pivotaltracker.com/story/show/156649006

**Comment by jbothma** [comment]
resolved
